image: atlassian/default-image:2
pipelines:
  custom: # defines that this can only be triggered manually or by a schedule
    master: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          script:
            - echo "Scheduled builds in Pipelines are awesome!"

  branches:
    master: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          script:
            - git remote add sync git@github.com:rakwal/test-pipeline-trigger.git
            - git checkout dev
            - git pull    
            - git push sync dev        