image: atlassian/default-image:2
pipelines:
  custom: # defines that this can only be triggered manually or by a schedule
    master: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          script:
            - echo "Scheduled builds in Pipelines are awesome!"