image: atlassian/default-image:2
pipelines:
  custom: # defines that this can only be triggered manually or by a schedule
    master: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          script:
            - echo "Scheduled builds in Pipelines are awesome!"
    qa:
      - step:
          script:
            - echo "qa branch"

  branches:
    dev: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          script:
            - git clone https://Sonal-Rakwal:Pk56tvYkLqqP3HGFFQE7@bitbucket.org/brevilledigital/test.git orig
            - git -C orig checkout dev
            - git clone https://kr79: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@github.com/rakwal/test-pipeline-trigger.git/ upstream
            - ls -lrt
            - git -C upstream checkout dev
            - cd upstream
            - ls -lrt
            - rm -rf *
            - cd ..
            - cp -r orig/* upstream/
            - git -C upstream add --all
            - git config --global user.email "arunkumar0305.ak@gmail.com" && git -C upstream commit -m "sync"
            - git config --global push.default matching
            - git -C upstream push